- name: Create ocp config dir
  ansible.builtin.file:
    path: "{{ sno_ocp_config_dir }}"
    state: directory
    mode: '0755'

- name: Read ssh pub key
  set_fact:
    ssh_pub_key: "{{ lookup('file', '~/.ssh/id_ed25519.pub') }}"

- name: Copy install-config to ocp config dir
  ansible.builtin.template:
    src: install-config.yaml.j2
    dest: "{{ sno_ocp_config_dir }}/install-config.yaml"

- name: Create ocp config
  ansible.builtin.shell: |
    /usr/local/bin/openshift-install --dir {{ sno_ocp_config_dir }} create single-node-ignition-config

- name: Embed ignition data into rhcos iso
  ansible.builtin.shell: |
   podman run --privileged --pull always --rm -v /dev:/dev -v /run/udev:/run/udev -v {{ sno_ocp_config_dir }}:/data -w /data quay.io/coreos/coreos-installer:release iso ignition embed -fi bootstrap-in-place-for-live-iso.ign {{ sno_iso_image_name }}

- name: Upload iso image to proxmox
  delegate_to: proxmox
  remote_user: root
  ansible.builtin.copy:
    src: "{{ sno_ocp_config_dir }}/{{ sno_iso_image_name }}"
    dest: "/var/lib/vz/template/iso/{{ sno_iso_image_name }}"

